"""init

Revision ID: 195bceedf162
Revises: 
Create Date: 2026-04-25 18:02:38.670416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '195bceedf162'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('registration_deadline', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('number_of_visitors', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status_changed_at', sa.DateTime(), nullable=False),
    sa.Column('place_id', sa.String(), nullable=True),
    sa.Column('place_name', sa.String(), nullable=True),
    sa.Column('place_city', sa.String(), nullable=True),
    sa.Column('place_address', sa.String(), nullable=True),
    sa.Column('place_seats_pattern', sa.String(), nullable=True),
    sa.Column('place_changed_at', sa.DateTime(), nullable=True),
    sa.Column('place_created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('last_sync_time', sa.DateTime(), nullable=False),
    sa.Column('last_changed_at', sa.DateTime(), nullable=False),
    sa.Column('sync_status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_metadata')
    op.drop_table('events')
    # ### end Alembic commands ###
